{
  "openapi": "3.0.0",
  "info": {
    "title": "Swagger Document for API Of DAgora",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url":"https://internal.c98staging.dev/adapters",
      "variables": {}
    },
    {
      "url": "http://localhost:3031/adapters",
      "variables": {}
    }
  ],
  "paths": {
    "/private/authen": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Get authorization token for admin Account",
        "operationId": "Get authorization token for admin Account",
        "requestBody": {
          "description": "Get token Authen for Account",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "example": "example@coin98.finance"
                  },
                  "password": {
                    "type": "string",
                    "example": "password"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/private/onchain": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Get Authorization token in OnchainSignature for Address by PrivateKey and Chain",
        "operationId": "Get Onchain signature for Address",
        "requestBody": {
          "description": "Get token Authen for Account",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "privateKey": {
                    "type": "string",
                    "example": "privateKey String"
                  },
                  "chain": {
                    "type": "string",
                    "example": "Chain name"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/": {
      "post": {
        "tags": [
          "Listing NFT"
        ],
        "summary": "Create listing request for nft in DAgora",
        "operationId": "create Activity ",
        "parameters": [
          {
            "name": "onChainSignature",
            "in": "header",
            "description": "Authen Token to verified Address",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {
          "description": "Data for listing NFT request in DAgora",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "address": {
                    "type": "string",
                    "example": "1234"
                  },
                  "chain": {
                    "type": "string",
                    "example": "matic"
                  },
                  "id": {
                    "type": "string",
                    "example": "matic"
                  },
                  "signature": {
                    "type": "string",
                    "example": "signature"
                  },
                  "signMessage": {
                    "type": "string",
                    "example": "signMessage"
                  },
                  "time": {
                    "type": "number",
                    "example": 123
                  },
                  "duration": {
                    "type": "number",
                    "example": 123
                  },
                  "amountUSD": {
                    "type": "number",
                    "example": 123
                  },
                  "tokens": {
                    "type": "array",
                    "example": [
                      "tokenAddress"
                    ]
                  },
                  "amount": {
                    "type": "string",
                    "example": "100000"
                  },
                  "tokenAddress": {
                    "type": "string",
                    "example": "tokenAddress"
                  },
                  "nonce": {
                    "type": "string",
                    "example": "10"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/mission/admx": {
      "get": {
        "tags": [
          "Mission Admin"
        ],
        "summary": "Get List Mission Admin filtered by name, chain",
        "operationId": "Get List Mission Admin filtered by name, chain",
        "parameters": [
          {  
            "name":"key",
            "in":"query",
            "description":"Keyword name of List Mission filter (example: abc)",
            "required":false,
            "type":"string"
          },
          {  
            "name":"chain",
            "in":"query",
            "description":"List Chains (example: solana, binanceSmart)",
            "required":false,
            "type":"string"
          },
          {  
            "name":"page",
            "in":"query",
            "description":"Page number of List Mission filter returns (default page = 1)",
            "required":false,
            "type":"number"
          },
          {  
            "name":"size",
            "in":"query",
            "description":"Size of page of List Mission filter returns (default size = 10)",
            "required":false,
            "type":"number"
          },
          {  
            "name":"sort",
            "in":"query",
            "description":"Sort by time ( newest: -time, oldest: time)",
            "required":false,
            "type":"number"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": [
                    "data",
                    "success",
                    "status"
                  ],
                  "properties": {
                    "data": {
                      "type": "object"
                    },
                    "success": {
                      "type": "boolean"
                    },
                    "status": {
                      "type": "number"
                    }
                  }
                },
                "example": {
                  "data": {
                    "data": [
                      {
                        "_id": "6423ba8c0579c9781dccb491",
                        "missionName": "HVN",
                        "missionAvatar": "avatar",
                        "partnerName": "C98",
                        "partnerLogo": "C98Logo",
                        "rewardImage": "image",
                        "totalRewardsMinted": 0,
                        "totalRewards": 98,
                        "startTime": "2023-03-18T08:33:27.124Z",
                        "endTime": "2023-05-25T08:33:27.124Z",
                        "status": "active"
                      },
                      {
                        "_id": "6423b53dde51d873a1337f3c",
                        "missionName": "Kyteck",
                        "missionAvatar": "avatar",
                        "partnerName": "C98",
                        "partnerLogo": "C98Logo",
                        "rewardImage": "image",
                        "totalRewardsMinted": 0,
                        "totalRewards": 150,
                        "startTime": "2023-03-18T08:33:27.124Z",
                        "endTime": "2023-05-25T08:33:27.124Z",
                        "status": "active"
                      },
                      {
                        "_id": "641df95acda4da3e9f188e81",
                        "missionName": "Saros Camp",
                        "missionAvatar": "avatar",
                        "partnerName": "C98",
                        "partnerLogo": "C98Logo",
                        "rewardImage": "iamge",
                        "totalRewardsMinted": 0,
                        "totalRewards": 150,
                        "startTime": "2023-01-18T08:33:27.124Z",
                        "endTime": "2023-02-25T08:33:27.124Z",
                        "status": "ended"
                      },
                      {
                        "_id": "641d5ba888d19e57a3450d03",
                        "missionName": "C98 Camp V2",
                        "missionAvatar": "avatar",
                        "partnerName": "C98",
                        "partnerLogo": "C98Logo",
                        "rewardImage": "iamge",
                        "totalRewardsMinted": 2,
                        "totalRewards": 1000,
                        "startTime": "2023-04-18T08:33:27.124Z",
                        "endTime": "2023-05-25T08:33:27.124Z",
                        "status": "upcoming"
                      }
                    ],
                    "total": 4,
                    "totalPage": 1,
                    "currentPage": 1
                  },
                  "success": true,
                  "status": 200
                }
              }
            },
            "headers": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "Mission Admin"
        ],
        "summary": "Create mission and setup mission tasks",
        "operationId": "Create mission and setup mission tasks",
        "parameters": [],
        "requestBody": {
          "description": "Data for Mission and Mission Tasks",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateSetupMissionDocumentRequest"
              },
              "example": {
                "inSequence": true,
                "mission": {
                    "partnerId": "641990ee27e5a924f2393b6f",
                    "collectionAddress":"Kyteck",
                    "missionName":"Kyteck",
                    "missionDescription":"joining",
                    "missionAvatar": "avatar",
                    "rewardImageExample": "image",
                    "rewardDescription": "reward",
                    "rewardUri" : "reward uri",
                    "totalRewards" : "150",
                    "chain" :"binanceSmart",
                    "startTime" : "2023-03-18 08:33:27.124Z",
                    "endTime": "2023-05-25 08:33:27.124Z"
                },
                "tasks": [
                    {
                      "taskTypeId": "onChain",
                      "taskContent" : {
                          "flatform" : "fb",
                          "flatformImage" : "image fb",
                          "taskName" : "follow",
                          "taskDescription" : "follow 10 people on fb",
                          "taskConfiguration" : {}
                      }
                    },
                    {
                      "taskTypeId": "onChain",
                      "taskContent" : {
                          "flatform" : "youtube",
                          "flatformImage" : "image youtube",
                          "taskName" : "follow",
                          "taskDescription" : "follow 10 people on youtube",
                          "taskConfiguration" : {}
                      }
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/mission/admx/item/{id}": {
      "put": {
        "tags": [
          "Mission Admin"
        ],
        "summary": "Update mission and setup mission tasks",
        "operationId": "Update mission and setup mission tasks",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ObjectId Mission (_id)",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {
          "description": "Data for Mission and Mission Tasks",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "inSequence": {
                    "type": "boolean",
                    "example": true
                  },
                  "mission": {
                    "$ref":"#/components/schemas/CreateMissionDocumentRequest"
                  },
                  "tasks": {
                    "$ref":"#/components/schemas/CreateMissionTaskDocumentRequest"
                  }
                }
              },
              "example": {
                "inSequence": true,
                "mission": {
                    "partnerId": "641990ee27e5a924f2393b6f",
                    "collectionAddress":"Kyteck",
                    "missionName":"Kyteck",
                    "missionDescription":"joining",
                    "missionAvatar": "avatar",
                    "rewardImageExample": "image",
                    "rewardDescription": "reward",
                    "rewardUri" : "reward uri",
                    "totalRewards" : "150",
                    "chain" :"binanceSmart",
                    "startTime" : "2023-03-18 08:33:27.124Z",
                    "endTime": "2023-05-25 08:33:27.124Z"
                },
                "tasks": [
                    {
                        "taskTypeId": "onChain",
                        "taskContent" : {
                            "flatform" : "fb",
                            "flatformImage" : "image fb",
                            "taskName" : "follow",
                            "taskDescription" : "follow 10 people on fb",
                            "taskConfiguration" : {}
                        }
                    },
                    {
                      "taskTypeId": "onChain",
                      "taskContent" : {
                          "flatform" : "youtube",
                          "flatformImage" : "image youtube",
                          "taskName" : "follow",
                          "taskDescription" : "follow 10 people on youtube",
                          "taskConfiguration" : {}
                      }
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/mission/user": {
      "get": {
        "tags": [
          "Mission User"
        ],
        "summary": "Get List Mission User filtered by name, chain, type, requirements, status",
        "operationId": "Get List Mission User filtered by name, chain, type, requirements, status",
        "parameters": [
          {  
            "name":"key",
            "in":"query",
            "description":"Keyword name of List Mission filter (example: abc)",
            "required":false,
            "type":"string"
          },
          {  
            "name":"chain",
            "in":"query",
            "description":"List Chains (example: solana, binanceSmart)",
            "required":false,
            "type":"string"
          },
          {  
            "name":"type",
            "in":"query",
            "description":"List type (example: active, upcoming, ended)",
            "required":false,
            "type":"string"
          },
          {  
            "name":"requirements",
            "in":"query",
            "description":"List requirements (example: onChain, offChain)",
            "required":false,
            "type":"string"
          },
          {  
            "name":"status",
            "in":"query",
            "description":"List status (example: notStarted, inProgress, finished, minted)",
            "required":false,
            "type":"string"
          },
          {  
            "name":"userAddress",
            "in":"query",
            "description":"userAddress (example: 123)",
            "required":false,
            "type":"string"
          },
          {  
            "name":"page",
            "in":"query",
            "description":"Page number of List Mission filter returns (default page = 1)",
            "required":false,
            "type":"number"
          },
          {  
            "name":"size",
            "in":"query",
            "description":"Size of page of List Mission filter returns (default size = 10)",
            "required":false,
            "type":"number"
          },
          {  
            "name":"sort",
            "in":"query",
            "description":"Sort by time ( newest: -time, oldest: time)",
            "required":false,
            "type":"number"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": [
                    "data",
                    "success",
                    "status"
                  ],
                  "properties": {
                    "data": {
                      "type": "object"
                    },
                    "success": {
                      "type": "boolean"
                    },
                    "status": {
                      "type": "number"
                    }
                  }
                },
                "example": {
                  "data": {
                    "data": [
                      {
                        "_id": "6423ba8c0579c9781dccb491",
                        "missionName": "HVN",
                        "missionAvatar": "avatar",
                        "partnerName": "C98",
                        "partnerLogo": "C98Logo",
                        "rewardImage": "image",
                        "totalRewardsMinted": 0,
                        "totalRewards": 98,
                        "startTime": "2023-03-18T08:33:27.124Z",
                        "endTime": "2023-05-25T08:33:27.124Z",
                        "status": "active"
                      },
                      {
                        "_id": "6423b53dde51d873a1337f3c",
                        "missionName": "Kyteck",
                        "missionAvatar": "avatar",
                        "partnerName": "C98",
                        "partnerLogo": "C98Logo",
                        "rewardImage": "image",
                        "totalRewardsMinted": 0,
                        "totalRewards": 150,
                        "startTime": "2023-03-18T08:33:27.124Z",
                        "endTime": "2023-05-25T08:33:27.124Z",
                        "status": "active"
                      },
                      {
                        "_id": "641df95acda4da3e9f188e81",
                        "missionName": "Saros Camp",
                        "missionAvatar": "avatar",
                        "partnerName": "C98",
                        "partnerLogo": "C98Logo",
                        "rewardImage": "iamge",
                        "totalRewardsMinted": 0,
                        "totalRewards": 150,
                        "startTime": "2023-01-18T08:33:27.124Z",
                        "endTime": "2023-02-25T08:33:27.124Z",
                        "status": "ended"
                      },
                      {
                        "_id": "641d5ba888d19e57a3450d03",
                        "missionName": "C98 Camp V2",
                        "missionAvatar": "avatar",
                        "partnerName": "C98",
                        "partnerLogo": "C98Logo",
                        "rewardImage": "iamge",
                        "totalRewardsMinted": 2,
                        "totalRewards": 1000,
                        "startTime": "2023-04-18T08:33:27.124Z",
                        "endTime": "2023-05-25T08:33:27.124Z",
                        "status": "upcoming"
                      }
                    ],
                    "total": 4,
                    "totalPage": 1,
                    "currentPage": 1
                  },
                  "success": true,
                  "status": 200
                }
              }
            },
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/mission/user/item/{id}": {
      "get": {
        "tags": [
          "Mission User"
        ],
        "summary": "Get Detail Mission User By ID",
        "operationId": "Get Detail Mission User By ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ObjectId Mission (_id)",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/mission/user/participant": {
      "post": {
        "tags": [
          "Mission User"
        ],
        "summary": "Create Participant Mission",
        "operationId": "Create Participant Mission",
        "requestBody": {
          "description": "Participant Mission",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "nftProfileAddress",
                  "missionId"
                ],
                "properties": {
                  "nftProfileAddress": {
                    "type": "string",
                    "example": "userAddress2"
                  },
                  "missionId": {
                    "type": "string",
                    "example": "641d5ba888d19e57a3450d03"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "CreateSetupMissionDocumentRequest": {
        "title": "CreateSetupMissionDocumentRequest",
        "required": [
          "mission",
          "tasks"
        ],
        "type": "object",
        "properties": {
          "inSequence": {
            "type": "boolean"
          },
          "mission": {
            "$ref": "#/components/schemas/CreateMissionDocumentRequest"
          },
          "tasks": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CreateMissionTaskDocumentRequest"
            }
          }
        },
        "example": {
          "inSequence": true,
          "mission": {
              "partnerId": "641990ee27e5a924f2393b6f",
              "collectionAddress":"Kyteck",
              "missionName":"Kyteck",
              "missionDescription":"joining",
              "missionAvatar": "avatar",
              "rewardImageExample": "image",
              "rewardDescription": "reward",
              "rewardUri" : "reward uri",
              "totalRewards" : "150",
              "chain" :"binanceSmart",
              "startTime" : "2023-03-18 08:33:27.124Z",
              "endTime": "2023-05-25 08:33:27.124Z"
          },
          "tasks": [
              {
                  "taskTypeId": "onChain",
                  "taskContent" : {
                      "flatform" : "fb",
                      "flatformImage" : "image fb",
                      "taskName" : "follow",
                      "taskDescription" : "follow 10 people on fb",
                      "taskConfiguration" : {}
                  }
              },
              {
                "taskTypeId": "onChain",
                "taskContent" : {
                    "flatform" : "youtube",
                    "flatformImage" : "image youtube",
                    "taskName" : "follow",
                    "taskDescription" : "follow 10 people on youtube",
                    "taskConfiguration" : {}
                }
            }
          ]
        }
      },
      "CreateMissionDocumentRequest": {
        "title": "CreateMissionDocumentRequest",
          "required": [
            "partnerId",
            "collectionAddress",
            "missionName",
            "missionDescription",
            "missionAvatar",
            "rewardImageExample",
            "rewardDescription",
            "rewardUri" ,
            "totalRewards" ,
            "chain" ,
            "startTime"
          ],
          "type": "object",
          "properties": {
            "partnerId": {
              "type": "string"
            },
            "collectionAddress": {
              "type": "string"
            },
            "missionName": {
              "type": "string"
            },
            "missionDescription": {
              "type": "string"
            },
            "missionAvatar": {
              "type": "string"
            },
            "rewardImageExample": {
              "type": "string"
            },
            "rewardDescription": {
              "type": "string"
            },
            "rewardUri": {
              "type": "string"
            },
            "totalRewards": {
              "type": "string"
            },
            "chain": {
              "type": "string"
            },
            "startTime": {
              "type": "string"
            },
            "endTime": {
              "type": "string"
            }
          },
          "example": {
            "partnerId": "641990ee27e5a924f2393b6f",
            "collectionAddress":"Kyteck",
            "missionName":"Kyteck",
            "missionDescription":"joining",
            "missionAvatar": "avatar",
            "rewardImageExample": "image",
            "rewardDescription": "reward",
            "rewardUri" : "reward uri",
            "totalRewards" : "150",
            "chain" :"binanceSmart",
            "startTime" : "2023-03-18 08:33:27.124Z",
            "endTime": "2023-05-25 08:33:27.124Z"
          }
      },
      "CreateMissionTaskDocumentRequest": {
        "title": "CreateMissionTaskDocumentRequest",
        "required": [
          "taskTypeId",
          "taskContent"
        ],
        "type": "object",
        "properties": {
          "taskTypeId": {
            "type": "string"
          },
          "taskContent": {
            "$ref": "#/components/schemas/CreateTaskContentDocumentRequest"
          }
        },
        "example": {
          "taskTypeId": "onChain",
          "taskContent" : {
              "flatform" : "youtube",
              "flatformImage" : "image youtube",
              "taskName" : "follow",
              "taskDescription" : "follow 10 people on youtube",
              "taskConfiguration" : {}
          }
        }
      },
      "CreateTaskContentDocumentRequest": {
        "title": "CreateTaskContentDocumentRequest",
        "required": [
          "flatform",
          "flatformImage",
          "taskName",
          "taskDescription",
          "taskConfiguration" 

        ],
        "type": "object",
        "properties": {
          "flatform": {
            "type": "string"
          },
          "flatformImage": {
            "type": "string"
          },
          "taskName": {
            "type": "string"
          },
          "taskDescription": {
            "type": "string"
          },
          "taskConfiguration": {
            "type": "object"
          }
        },
        "example": {
          "flatform" : "fb",
          "flatformImage" : "image fb",
          "taskName" : "follow",
          "taskDescription" : "follow 10 people on fb",
          "taskConfiguration" : {}
        }
      }  
    },
    "securitySchemes": {
      "httpBearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "httpBearer": ""
    }
  ],
  "tags": [
    {
      "name": "Authentication",
      "description": "API to get Authentication token for api in DAgora"
    },
    {
      "name": "Listing NFT",
      "description": "API for Listing NFT in DAgora marketplace"
    },
    {
      "name": "Mission Admin",
      "description": "API for create, read, update Mission of Admin"
    },
    {
      "name": "Mission Admin",
      "description": "API for create, read, update Mission of User"
    }
  ]
}